services:
  - type: web
    name: reddit-analyzer-api
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: >
      gunicorn reddit_api:app
               --bind 0.0.0.0:$PORT
               --worker-class gthread
               --threads 4
               --workers 2
               --timeout 180
    envVars:
      - key: GUNICORN_CMD_ARGS
        value: "--log-level info"
    python:
      version: "3.11"  
