services:
  - type: web
    name: reddit-analyzer-api
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn reddit_api:app -c gunicorn.conf.py"
    # NO environment variables with secrets here!
    python:
      version: "3.11"
